steps:

- checkout: self

- script: |
    terraform version
  displayName: Verify Terraform

- task: AzureCLI@2
  displayName: Azure Login
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az account show

- script: |
    terraform init
    terraform validate
  workingDirectory: terraform
  displayName: Terraform Validate

- task: AzureCLI@2
  displayName: Terraform Plan
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd terraform
      terraform plan \
        -var="tenant_id=$(az account show --query tenantId -o tsv)"
