trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- script: terraform fmt -check
  workingDirectory: terraform
  displayName: Terraform Format Check

- script: |
    terraform init
    terraform validate
  workingDirectory: terraform
  displayName: Terraform Validate
